apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus-dev
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      containers:
        - name: directus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8055
          envFrom:
            - configMapRef:
                name: directus-config-dev
            - secretRef:
                name: directus-secret-dev
          volumeMounts:
            - mountPath: "/directus/uploads"
              name: directus-storage
      volumes:
        - name: directus-storage
          persistentVolumeClaim:
            claimName: directus-nfs-pvc-dev
