apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-nfs-pvc-dev
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: directus-nfs-pv-dev
