apiVersion: v1
kind: PersistentVolume
metadata:
  name: directus-nfs-pv-test
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  nfs:
    server: {{ .Values.persistence.nfsServer }}
    path: "{{ .Values.persistence.nfsPath }}"
  mountOptions:
  - vers=4.1
  - sec=sys
